#!/bin/bash

# generate list of all installed packages
pacman -Q > ~/scripts/pkglist.txt

# backup user scripts
rsync -Ea --delete ~/scripts ~/storage/Documents/linux_sync

# Backup documents
rsync -a --delete ~/Documents ~/storage/Documents/linux_sync

# sync various folders on storage partition with AWS

aws s3 sync ~/storage/Videos/ s3://x230-232523u-backup/Videos/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini";

aws s3 sync ~/storage/Documents/ s3://x230-232523u-backup/Documents/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini";

aws s3 sync ~/storage/Music/ s3://x230-232523u-backup/Music/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini";

aws s3 sync ~/storage/Pictures/ s3://x230-232523u-backup/Pictures/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini";

# aws s3 sync ~/storage/Videos/ s3://x230-232523u-backup/Videos/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini" --dryrun
# aws s3 sync ~/storage/Documents/ s3://x230-232523u-backup/Documents/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini" --dryrun
# aws s3 sync ~/storage/Music/ s3://x230-232523u-backup/Music/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini" --dryrun
# aws s3 sync ~/storage/Pictures/ s3://x230-232523u-backup/Pictures/ --storage-class STANDARD_IA --no-follow-symlinks --delete --exclude "*.ini" --dryrun
