#!/bin/bash
if ((EUID != 0)); then
  echo >&2 "Error: Missing root privilege"
  exit 1
fi
clear
echo "Set charging profile configuration"
select var in "Full" "Limited" "Inhibit Charge" "Allow Charge" "Force Discharge" "Stop Discharge" "Report" "Power Cycle"; do
	case $var in
		"Full" ) tlp setcharge 96 99 BAT0 > /dev/null; break ;;
		"Limited" ) tlp setcharge 75 80 BAT0 > /dev/null; break ;;
		"Inhibit Charge" ) echo "Set min option: "; read min_option ; tpacpi-bat -s IC 1 1 $min_option; break ;;
		"Allow Charge" ) tpacpi-bat -s IC 1 0; break ;;
		"Force Discharge" ) tpacpi-bat -s FD 1 1; break ;;
		"Stop Discharge" ) tpacpi-bat -s FD 1 0; break ;;
		"Report" ) break ;;
		"Power Cycle" ) echo "Cycling Power..." ; tpacpi-bat -s FD 1 1; 
			for x in {1..5} 
			do 
				echo -n $x
				sleep 0.5 
				echo -n "..."
				sleep 0.5
			done ; 
			echo ;
			tpacpi-bat -s FD 1 0; break ;;
	esac
done
echo "----------"
sleep 1
batstat="$(tlp-stat -b)"
batstat="$(sed 's/Unknown/Not Charging/' <<< $batstat)"
printf "%-16s %s \n" \
	'Current Charge:' "$(echo "$batstat" | awk '/^Charge/ {printf "%.1f%%\n", $3}')" \
	'Battery Status:' "$(echo "$batstat" | awk '/status/ {printf "%s %s %s %s\n", $3, $4, $5, $6}')" \
	'Start Threshold:' "$(echo "$batstat" | awk '/start/ {printf "%.0f%%\n", $3}')" \
	'Stop Threshold:' "$(echo "$batstat" | awk '/stop/ {printf "%.0f%%\n", $3}')" \
	'Inhibit Charge:' "$(tpacpi-bat -g IC 1)" \
	'Force Discharge:' "$(tpacpi-bat -g FD 1)"
echo "----------"
